name: fill_and_sign
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dotted_border: ^2.0.0+2
  equatable: ^2.0.3
  file_picker: ^4.2.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  image_gallery_saver: ^1.7.1
  material_design_icons_flutter: ^5.0.6595
  open_file: ^3.2.1
  path_provider: ^2.0.8
  pdf_render: ^1.0.18
  permission_handler: ^8.3.0
  share: ^2.0.4
  shared_preferences: ^2.0.11
  signature: ^4.1.1
  syncfusion_flutter_pdf: ^19.3.57-beta
  thumbnailer: ^2.0.1
  uuid: ^3.0.5

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.0.17

flutter_icons:
  android: true
  ios: true
  image_path_ios: "assets/images/launcher/logo-launcher-signer-ios.png"
  image_path_android: "assets/images/launcher/logo-launcher-signer-android.png"
  adaptive_icon_background: "assets/images/launcher/background-launcher-icon.png"
  adaptive_icon_foreground: "assets/images/launcher/logo-foreground.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
  
  fonts:
    - family: Austein
      fonts:
        - asset: assets/fonts/austein/Austein.ttf